# ==========================================================
# Application
# ==========================================================
spring.application.name=cep-search-api
spring.profiles.active=${APP_PROFILE:local}
server.port=8080
server.servlet.context-path=/@project.name@

# ==========================================================
# Project Info
# ==========================================================
info.application.name=@project.name@
info.application.description=@project.description@
info.application.version=@project.version@
info.application.group-id=@project.groupId@
info.application.artifact-id=@project.artifactId@
info.application.java-version=@java.version@
info.application.encoding=@project.build.sourceEncoding@
spring.banner.location=classpath:banner.txt

# ==========================================================
# Swagger Info
# ==========================================================
springdoc.swagger-ui.path=/@project.name@
springdoc.swagger-ui.use-root-path=true

# ==========================================================
# Actuator
# ==========================================================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
management.info.env.enabled=true